language: php

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DRUPAL_TEST_MODULE_NAME: ctools_api
    - DRUPAL_TEST_MODULE_LOCATION: sites/all/modules/contrib
    - DRUPAL_TEST_INSTALL_PROFILE: minimal

# https://docs.travis-ci.com/user/database-setup/#MySQL
mysql:
  database: drupal
  username: travis
  encoding: utf8

before_install:
  # Go to the directory where everything will happen.
  - cd ./tests/travis
  # Inject custom PHP configuration.
  - phpenv config-add php/php.ini
  # Install dependencies.
  - composer install
  # Compute facts.
  - export CWD="$(pwd -P)"
  # Make our packages available globally.
  - export PATH="$CWD/bin:$PATH"
  # Read the name of a directory with Drupal from "composer.json".
  - export DRUPAL_TEST_SUBDIR="$(awk '/type:drupal-core/ {print $1}' < "$CWD/composer.json" | tr -d '"/:')"
  # Use the subdirectory with Drupal as a name of the database (dashes are
  # replaced by underscores).
  - export DRUPAL_TEST_DATABASE_NAME="${DRUPAL_TEST_SUBDIR//-/_}"
  # Save origin directory of a build.
  - export TRAVIS_BUILD_DIR_OLD="$TRAVIS_BUILD_DIR"
  # Override the directory of a build.
  - export TRAVIS_BUILD_DIR="$CWD/$DRUPAL_TEST_SUBDIR/$DRUPAL_TEST_MODULE_LOCATION/$DRUPAL_TEST_MODULE_NAME"
  # Print modified environment.
  - env
  # Ensure the directory for project exists.
  - mkdir -p "$TRAVIS_BUILD_DIR"
  # Relocate the project.
  - rsync -ra --delete --exclude="${CWD//$TRAVIS_BUILD_DIR_OLD\//}" "$TRAVIS_BUILD_DIR_OLD" "$TRAVIS_BUILD_DIR"
  # Discover available coding standards.
  - phpcs --config-set installed_paths "$(find "$CWD/vendor/" -type f -name "ruleset.xml" -exec dirname {} \; | xargs dirname | uniq | paste -sd "," -)"
  # Enable Apache modules.
  - sudo a2enmod rewrite actions fastcgi alias
  - sudo service apache2 restart

install:
  # Go to the directory with Drupal.
  - cd "$CWD/$DRUPAL_TEST_SUBDIR"
  # Run PHPCS against the codebase of our project.
  - phpcs "$TRAVIS_BUILD_DIR" --runtime-set testVersion "$TRAVIS_PHP_VERSION"
  # Install the Drupal.
  - drush si "$DRUPAL_TEST_INSTALL_PROFILE" --db-url="mysql://$USER:@127.0.0.1/$DRUPAL_TEST_DATABASE_NAME" -y -v

script:
  - drush en "$DRUPAL_TEST_MODULE_NAME" -y
