language: php

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DRUPAL_TESTING_MODULE: ctools_api
  - DRUPAL_DATABASE_NAME: drupal
  - DRUPAL_DATABASE_USER: travis
  - PATH="$HOME/.composer/vendor/bin:$PATH"

# https://docs.travis-ci.com/user/database-setup/#MySQL
mysql:
  database: drupal
  username: travis
  encoding: utf8

before_install:
  - mv ./tests/travis/ ../../build/
  - cd ../../build/
  - phpenv config-add php/php.ini
  - composer install
  - mv "$TRAVIS_BUILD_DIR/" "drupal/sites/all/modules/contrib/$DRUPAL_TESTING_MODULE/"
  - phpenv rehash
  - env

install:
  - drush si minimal --db-url="mysql://$DRUPAL_DATABASE_USER:@127.0.0.1/$DRUPAL_DATABASE_NAME" -y -v
  - sudo service apache2 restart

script:
  - drush en "$DRUPAL_TESTING_MODULE" -y
