language: php

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DRUPAL_TESTING_MODULE: ctools_api
    - DRUPAL_DATABASE_NAME: drupal
    - PATH: "$HOME/.composer/vendor/bin:$PATH"

# https://docs.travis-ci.com/user/database-setup/#MySQL
mysql:
  database: drupal
  username: travis
  encoding: utf8

before_install:
  # Go to the directory where everything will happen.
  - cd ./tests/travis/
  # Inject custom PHP configuration.
  - phpenv config-add php/php.ini
  # Install dependencies.
  - composer install
  # Override the path to directory with a build.
  - export TRAVIS_BUILD_DIR="drupal/sites/all/modules/contrib/$DRUPAL_TESTING_MODULE"
  # Ensure the directory exists.
  - mkdir -p "$TRAVIS_BUILD_DIR/"
  # Copy the module.
  - mv ./!(tests) "$TRAVIS_BUILD_DIR/"
  # Discover available coding standards.
  - phpcs --config-set installed_paths "$(find vendor/ -type f -name "ruleset.xml" -exec dirname {} \; | xargs dirname | uniq | paste -sd "," -)"
  - a2enmod rewrite actions fastcgi alias
  - phpenv rehash
  - env

install:
  - drush si minimal --db-url="mysql://$USER:@127.0.0.1/$DRUPAL_DATABASE_NAME" -y -v
  - sudo service apache2 restart

script:
  - phpcs --standard=Drupal "$TRAVIS_BUILD_DIR/"
  - phpcs --standard=PHPCompatibility "$TRAVIS_BUILD_DIR/"
  - drush en "$DRUPAL_TESTING_MODULE" -y
