language: php

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DRUPAL_TESTING_MODULE: ctools_api
    - DRUPAL_DATABASE_NAME: drupal
    - PATH: "$TRAVIS_BUILD_DIR/tests/travis/bin:$PATH"

# https://docs.travis-ci.com/user/database-setup/#MySQL
mysql:
  database: drupal
  username: travis
  encoding: utf8

before_install:
  - env
  - sudo bash scripts/before_install.sh

install:
  - drush si minimal --db-url="mysql://$USER:@127.0.0.1/$DRUPAL_DATABASE_NAME" -y -v
  - sudo service apache2 restart

script:
  - ls -la "$TRAVIS_BUILD_DIR/"
  - phpcs "$TRAVIS_BUILD_DIR/" --standard=Drupal
  - phpcs "$TRAVIS_BUILD_DIR/" --standard=PHPCompatibility --runtime-set testVersion "$TRAVIS_PHP_VERSION"
  - drush en "$DRUPAL_TESTING_MODULE" -y
